Add resume of RAG's article
joaoarthurbm/academic pull request #3
Opened 2024-02-21 19:28 UTC by victorbrandaoa

2024-03-11 12:41 UTC, joaoarthurbm requested changes
comentários inline

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +LLMs pré-treinados tem mostrado conseguir armazenar conhecimento factual oriundo dos dados em seus parâmetros. No entanto, sua habilidade de acessar e precisamente manipular conhecimento ainda é limi
ok!

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +LLMs pré-treinados tem mostrado conseguir armazenar conhecimento factual oriundo dos dados em seus parâmetros. No entanto, sua habilidade de acessar e precisamente manipular conhecimento ainda é limi
Acho que esse seja um dos problemas. O outro problema é que, mesmo com origem, os modelos são generalistas e precisam de mais contexto para desempenharem melhor. RAG fornecesse isso. Coloca isso, por favor, @victorbrandaoa , antes de eu aceitar o PR.

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +Os autores propõe duas formas de marginalizar sobre os documentos recuperados para produzir uma distribuição sobre o texto gerado, são elas o RAG-Token e o RAG-Sequence.
marginzalizar sobre documentos? O que é isso?

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +Os autores propõe duas formas de marginalizar sobre os documentos recuperados para produzir uma distribuição sobre o texto gerado, são elas o RAG-Token e o RAG-Sequence.
Explicar o que é marginalizar nesse contexto.

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +De maneira geral achei o artigo bastante complexo e difícil de acompanhar, e apesar de ter entendido a ideia geral do artigo, ao meu ver esse artigo precisa de um background muito bom para entender c
Isso aqui é importante. Talvez a gente precise levantar artigos que ajudem a entender esse melhor.

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +Deixar aqui os comentários e insights importantes que surgiram durante a discussão do paper com o grupo. Colocar aqui ideias de trabalhos de pesquisa que podem ser feitas a partir desse trabalho. Por
E aí, @victorbrandaoa ?

2024-03-11 12:41 UTC, joaoarthurbm commented on papers-llm-code-review/rag.md
> +Deixar aqui os comentários e insights importantes que surgiram durante a discussão do paper com o grupo. Colocar aqui ideias de trabalhos de pesquisa que podem ser feitas a partir desse trabalho. Por
Acho que é importantítssimo você preencher essa seção com a relação ao que você está fazendo ou pretende fazer. Podemos nos inspirar na metodologia de avaliação? descobriu ferramentas que podem nos ajudar? talvez essa seja a parte mais importante do review.

2024-03-13 17:57 UTC, victorbrandaoa commented on papers-llm-code-review/rag.md
> +LLMs pré-treinados tem mostrado conseguir armazenar conhecimento factual oriundo dos dados em seus parâmetros. No entanto, sua habilidade de acessar e precisamente manipular conhecimento ainda é limi
Feito.

2024-03-13 17:57 UTC, victorbrandaoa commented on papers-llm-code-review/rag.md
> +Os autores propõe duas formas de marginalizar sobre os documentos recuperados para produzir uma distribuição sobre o texto gerado, são elas o RAG-Token e o RAG-Sequence.
Feito.

2024-03-13 17:57 UTC, victorbrandaoa commented on papers-llm-code-review/rag.md
> +De maneira geral achei o artigo bastante complexo e difícil de acompanhar, e apesar de ter entendido a ideia geral do artigo, ao meu ver esse artigo precisa de um background muito bom para entender c
Concordo total, estou inclusive buscando esses materiais.

2024-03-13 17:57 UTC, victorbrandaoa commented on papers-llm-code-review/rag.md
> +Deixar aqui os comentários e insights importantes que surgiram durante a discussão do paper com o grupo. Colocar aqui ideias de trabalhos de pesquisa que podem ser feitas a partir desse trabalho. Por
Feito.

2024-03-20 18:19 UTC, merged